### ISSUE TITLE
possible new johnoliver sub: r/floridaman

### ISSUE THREAD

**Issue by robertafreese** [username-is-required/reddark-subinfo#132] opened 2023-06-20 21:30 UTC
Posted poll results
https://old.reddit.com/r/FloridaMan/comments/14en9yd/the_future_of_rfloridaman_the_people_have_spoken/ 
No posts yet.

**Comment by username-is-required** [comment] 2023-06-20 21:55
cheers for flagging! (i’m guessing it’ll be picked up by the bot when it next runs in about 10 minutes, but i’ll close its issue as a dupe of this as you got there first lol)

**Comment by username-is-required** [comment] 2023-06-20 22:01
even though there are no posts yet, i think the post (and a mod comment left in response to a query) 

> A staggering 1,200 votes, making up a significant 35%, were cast in favor of reopening the subreddit. However, there was a stipulation attached to this decision—every post from now on must mention John Oliver.
> 
> Now, although I may hold a relatively humble position within Reddit's hierarchy of landed gentry, this, my dear friends, appears to be democracy in action. The voice of the people has resounded, and it seems they have an overwhelming affinity for John Oliver.
> 
> Therefore, as a result of the people's will and their resounding verdict, I hereby decree that all posts within this esteemed subreddit must incorporate a comparison between Florida Man and John Oliver. It's a quirky requirement, I must say, but one that we shall abide by henceforth. Let the era of John Oliver comparisons commence!

mod comment:
> Added a new auto-mod rule, titles must contain "John Oliver" - if they don't, the post will be automatically removed with some messaging on why.

**Closed** 2023-06-20 22:04 UTC

**Comment by username-is-required** [comment] 2023-06-20 22:08
the first post is here. and how truly fitting a post it is indeed

![IMG_9463](https://github.com/username-is-required/reddark-subinfo/assets/136007111/6091b734-a3dc-4dff-9370-79ca24d5d961)
